### ISSUE TITLE
Why can not re-queue the object if exceed failure limit 

### ISSUE THREAD

**Issue by smileusd** [kubernetes-sigs/sig-storage-lib-external-provisioner#113]
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/853cdd7cba6e20753071cdb3e07fe37a6f2fc5a3/controller/controller.go#L942

link to https://github.com/kubernetes-csi/external-provisioner/issues/671

**Comment by msau42** [comment]
I agree we should always retry forever. It looks like the library supports setting 0 to mean retry forever, and we are setting it to 0 in external-provisioner:
https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L354

Are you seeing different behavior?
