### ISSUE TITLE
Controller is unresponsive to context cancellation passed to Run(ctx context.Context)

### ISSUE THREAD

**Issue by MatthiasWerning** [kubernetes-sigs/sig-storage-lib-external-provisioner#155]
It seems to me that the provisioning controller does not react to any context cancellation that was passed down the chain from the calling application / library. 

This is probably due to the `select {}` statement in line 862 of `controller/controller.go`. Thus the `claimQueue` and `volumeQueue` will effectively never be shutdown since the local `run(ctx context.Context)` function never returns (with exception to an unsuccessful cache sync await).

Would be great if this could be fixed in v8 as well. This probably just requires the `select {}` to be replaced by `<-ctx.Done()` as far as I tried it using my own provisioning controller.

**Comment by jsafrane** [comment]
@MatthiasWerning do you mind sending a pull request? Master first, but we can fix release-8.0 too.

**Comment by MatthiasWerning** [comment]
Closed in favor of #159
