### ISSUE TITLE
I didn't find the ISCSI installation configuration

### ISSUE THREAD

**Issue by tengdagg** [kubernetes-sigs/sig-storage-lib-external-provisioner#157]
I didn't find the ISCSI installation configuration, the previous one doesn't work anymore, Kubernetes 1.27.3

**Comment by tengdagg** [comment]
@jsafrane It was in the warehouse before this https://github.com/kubernetes-retired/external-storage/tree/master/iscsi/targetd/kubernetes But I'm not sure if this is still available. I haven't found any related projects in the current warehouse

**Comment by jsafrane** [comment]
sig-storage-lib-external-provisioner is just a small part of the original external-storage repo. External-storage has been archived because it was too big and its iscsi part did not have any maintainers that wanted to continue with iscsi provisioner elsewhere.
