### ISSUE TITLE
Will the pv name be customizable?

### ISSUE THREAD

**Issue by zjuliuf** [kubernetes-sigs/sig-storage-lib-external-provisioner#166]
The pv name consists of prefix 'pvc-' and UID of the pending pvc currently. Will the pv name be customizable? 

// getProvisionedVolumeNameForClaim returns PV.Name for the provisioned volume.
// The name must be unique.
func (ctrl *ProvisionController) getProvisionedVolumeNameForClaim(claim *v1.PersistentVolumeClaim) string {
	return "pvc-" + string(claim.UID)
}

**Comment by zjuliuf** [comment]
Looking forward to getting your reply. Thanks a lot! @gnufied @mortent @Atoms @pohly

**Comment by niranjandarshann** [comment]
@zjuliuf  Yes, the name of the persistent volume (PV) can be customized. By default, it consists of the prefix 'pvc-' followed by the unique identifier (UID) of the pending persistent volume claim (PVC).

**Comment by niranjandarshann** [comment]
However, you can specify a custom name for the PV when you create it manually. This involves creating a PV definition in a YAML file where you can define your desired name for the PV.

**Comment by zjuliuf** [comment]
@niranjandarshann Thank you for your reply. As you mentioned, we can specify a custom name for the PV only when we create it manually. Whether can we specify a custom name for the PV when the PV is created dynamically by volume provisioner?

**Comment by jsafrane** [comment]
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/178 has been merged recently, the next release will have a callback to provide a PV name.
/close
