### ISSUE TITLE
Replace gometalinter

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/sig-storage-lib-external-provisioner#168]
This repository still uses github.com/alecthomas/gometalinter to ensure go code quality. The metalinter has been deprecated and archived since 2019. We must either remove it or replace it with a different linter, for example go vet or golangci-lint.

1. `Makefile` and `repo-infra/verify` scripts must be updated with the new linter. 
2. All issues found by the new linter must be fixed.

/help

**Comment by rihib** [comment]
@jsafrane Hello, is this issue already resolved by #167 ? It appears that metalinter has already been removed and govet is being used.

**Comment by niranjandarshann** [comment]
@jsafrane  I have noticed #167 have resolved this concern as metalinter has aleady removed and govet is being used so we may now close this issue. As i think the issue is well reported and resolved.

**Comment by jsafrane** [comment]
Alright, I wanted to check what linters are around and if any of them would be useful, but `go vet` could be enough
/close
