### ISSUE TITLE
unknown field 'Cap' in struct literal of type wait.Backoff

### ISSUE THREAD

**Issue by ariep** [kubernetes-sigs/sig-storage-lib-external-provisioner#18]
```
vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:543:4: unknown field 'Cap' in struct literal of type wait.Backoff
```
This is introduced by ac882d9c68b5ace8fdb17535a9ed1d335ebd5cef. Am I missing a constraint on a dependency version?

**Comment by ariep** [comment]
I see, thanks.

Let's assume I want to stay with kubernetes 1.13 for now. The 2.1.0 release contains the problematic commit, so I can't use that, right? The release info says "Use with 1.13 kubernetes libraries (k8s.io/client-go kubernetes-1.13*, k8s.io/apimachinery kubernetes-1.13*, etc.)" but that's not correct then?

Go newbie question: how do I specify a release in the `Gopkg.toml`? I can specify a branch, but the `release-1.13` branch also contains the problematic commit, so that's out. I guess I can specify a `revision` with a commit that works for me, but that is recommended against in the docs.

**Comment by wongma7** [comment]
The commit is there in the 1.13 branch and 2.1.0, but I amended it so it
works with 1.13.

For version, try ‘version = “v2.1.0”’ instead of ‘branch = ...’

**Comment by wongma7** [comment]
yes let's call it a backport...

For glog, anything will work. For k8s.io/* repos, generally you want them all to be the same version, so I would recommend setting 'version = "kubernetes-1.13.1"' for all of them in your Gopkg.toml and doing `dep ensure` again. You should only need to worry about dependency stuff if things don't compile, hopefully dep is smart enough to figure it out for you.
