### ISSUE TITLE
RFC: versioning and releasing

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/sig-storage-lib-external-provisioner#2]
Goal: copy client-go https://github.com/kubernetes/client-go#versioning as much as possible.
- Start with 1.0.0: release 1.0.0 compatible with 1.12 k8s.io/* libraries and 2.0.0 compatible with 1.13 k8s.io/* libraries. Compatible meaning you can vendor this and k8s.io/* at the same time without trouble.
- Maintain release-1.x branches, starting with 1.12 and 1.13.
- For each release-1.x branch, maintain an example that shows/proves how to vendor the lib alongside 1.x k8s.io/* libraries.
- TODO: do the same as above but with modules.
- Never check in Gopkg.* or vendor.

**Comment by jsafrane** [comment]
Would it make sense to have the same numbering as either client-go or kubernetes releases?

**Comment by wongma7** [comment]
i would like to copy kubernetes releases but there is a small chance we may break our little interface again in which case we want to be able to increment the major version without getting "out-of-step".

Maybe we could suffix each release with its corresponding kube release, it may be more confusing than useful though

**Comment by jsafrane** [comment]
Can we follow client-go then? It bumps major version pretty often :-)

**Comment by wongma7** [comment]
Yeah I can't think of a strong reason not to follow client-go..maybe because starting at v9.0.0 feels bad. If no objections I'll tag a v9.0.0 and v10.0.0-alpha later to match client-go... They basically release a x.0.0 every kubernetes release, and they have only made 1 bugfix release (v5.0.1) in the past. Prior to that their versioning was nonexistent/messy.

**Comment by wongma7** [comment]
versioning seems okay now.

we can't copy client-go after all since we want to be able to make breaking changes outside of kube release cycle like with v4.0.0
