### ISSUE TITLE
PV can't be deleted manually, if the reclaimpolicy is 'retain'

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/sig-storage-lib-external-provisioner#20]
When the reclaimpolicy is `retain`, PV is stuck at terminating after delete manually.
```
NAME                                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS            CLAIM                  STORAGECLASS         REASON    AGE
pvc-5b4fbbfd-f121-11e8-b5ad-00505634e8af         1Gi        RWX            Retain           Terminating       default/test-pvc       test-sc                        20m
```
I guess that's because the `finalizer` for PV is not removed.
```
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
```

If delete that `finalizer` manually, PV will be deleted normally.

I know that it will not send any requests to the provisioner if reclaimpolicy  is `retain`.
If so, who can erase that `finalizer`?

(Tested K8s Version: v1.10.11)

**Comment by wongma7** [comment]
A possible issue is if somebody edits the PV's reclaim policy after the provisioner has decided whether to put the finalizer on it. But that will require the provisioner to watch the PVs, I am not sure it is worth the trouble.

**Comment by wongma7** [comment]
finalizer was turned off by default, closing for now.
