### ISSUE TITLE
failure running against k8s.io/ master

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/sig-storage-lib-external-provisioner#30]
`make verify` fails with

```
# sigs.k8s.io/sig-storage-lib-external-provisioner/vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller
vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go:690:30: not enough arguments in call to resourcelock.New
	have (string, string, string, "sigs.k8s.io/sig-storage-lib-external-provisioner/vendor/k8s.io/client-go/kubernetes/typed/core/v1".CoreV1Interface, resourcelock.ResourceLockConfig)
	want (string, string, string, "sigs.k8s.io/sig-storage-lib-external-provisioner/vendor/k8s.io/client-go/kubernetes/typed/core/v1".CoreV1Interface, "sigs.k8s.io/sig-storage-lib-external-provisioner/vendor/k8s.io/client-go/kubernetes/typed/coordination/v1".CoordinationV1Interface, resourcelock.ResourceLockConfig)
```

**Comment by CommanderJax** [comment]
@dims Has this been fixed? I'm experiencing the same issue when attempting to build the example hostpath provisioner.

**Comment by dims** [comment]
@CommanderJax if you have my change from https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/31 (should be in master), then you should make sure that your `sig-storage-lib-external-provisioner` directory is under your `$GOPATH/src/sigs.k8s.io/` Then it will work. please try and let me know.

**Comment by CommanderJax** [comment]
@dims Thanks for referencing the issue, it makes sense now. The example hostpath provisioner's dependency path hasn't been updated which resulted in old lib being pulled. 

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/examples/hostpath-provisioner/Gopkg.toml#L34

Needs to be replaced with:

[[constraint]]
  branch = "master"
  name = "sigs.k8s.io/sig-storage-lib-external-provisioner"
