### ISSUE TITLE
Using sigs.k8s.io?

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-lib-external-provisioner#36]
How about using shorter URL prefix sigs.k8s.io which redirects to https://sigs.k8s.io?

**Comment by msau42** [comment]
I think it's done? https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/31

**Comment by cofyc** [comment]
Oh, didn’t check latest master.
/close
