### ISSUE TITLE
PV stuck in Release/Terminated state

### ISSUE THREAD

**Issue by pure-yesmat** [kubernetes-sigs/sig-storage-lib-external-provisioner#42]
We ran into the case where the PVC was deleted and the DeletionTimestamp was set on the PV. Example:

```
# kubectl get pv/pvc-fad3f3ed-6096-11e9-b725-aa00c744c95d
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM               
pvc-fad3f3ed-6096-11e9-b725-aa00c744c95d   1Gi        RWO            Delete           Terminating   default/pvc-74vqq

# kubectl get pv/pvc-fad3f3ed-6096-11e9-b725-aa00c744c95d -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pure-provisioner
  creationTimestamp: 2019-04-16T22:28:42Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2019-04-16T22:28:43Z
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
  name: pvc-fad3f3ed-6096-11e9-b725-aa00c744c95d
  resourceVersion: "1059"
```

It seems this line is the cause of the issue:

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/1ac0505e75cdb0524aec7f78b7c9ba99716208e4/controller/controller.go#L1115

This was added in commit: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/commit/9396ddf5d2690e5e6c8e2e1da288022d249cf067

In this case the line above prevents the PV from ever being deleted.
This was tested on K8s 1.11.

Is it not expected that the deletionTimestamp is set?

**Comment by wongma7** [comment]
if you updated the provisioner to a recent version where the finalizer feature is off by default then the PV won't be deleted if it was created by an earlier version of the provisioner where the finalizer feature was on by default. This means you will have to either reconfigure the provisioner to turn the finalizer feature on (pass AddFinalizer(true) to the controller) or remove the finalizer manually for these older PVs. Sorry about the inconvenience.
