### ISSUE TITLE
dep init failed with "No versions of golang.org/x/crypto met constraints"

### ISSUE THREAD

**Issue by tkokok** [kubernetes-sigs/sig-storage-lib-external-provisioner#45]
I have try many times and some versions of golang(1.10.8,1.11.5,1.12.5)/dep but it still not work, plz help me.  error stack following, after cmd "dep init" .
I can only create the vendor dir manualy and use "go get xxx" instead >.< , is there any solution ?
by the way, I'm working on PaaS layer and now try to integrate a new storage solution instead of the old one. I just wana use this library to create a StorageClass with dynamic provisioner

> Importing configuration from godep. These are only initial constraints, and are further refined during the solve process.
init failed: unable to solve the dependency graph: Solving failure: No versions of golang.org/x/crypto met constraints:
	master: unable to update checked out version: fatal: reference is not a tree: cbcb750295291b33242907a04be40e80801d0cfc
: command failed: [git checkout cbcb750295291b33242907a04be40e80801d0cfc]: exit status 128
	release-branch.go1.11: Could not introduce golang.org/x/crypto@release-branch.go1.11, as it is not allowed by constraint master from project github.com/miekg/dns.
	release-branch.go1.12: Could not introduce golang.org/x/crypto@release-branch.go1.12, as it is not allowed by constraint master from project github.com/miekg/dns.

**Comment by wongma7** [comment]
Not sure about this, sorry. From googling around it seems like an issue with dep's local cache. Please try using the existing toml and `mv .Gopkg.toml Gopkg.toml` and make sure you're on a release branch/tag. Probably the repo should move to go.mod soon.
