### ISSUE TITLE
Logs to console

### ISSUE THREAD

**Issue by iyurev** [kubernetes-sigs/sig-storage-lib-external-provisioner#48]
Good day!

How can I enable send provisioner logs to stderr or stdout, in glog documentation explain this case , but look like in https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go there is no implementation for this..

**Comment by jsafrane** [comment]
The library itself does not control destination of logs, it's task either for an application that uses the library or (more often) user that uses the app. Check glog / klog command line arguments: https://godoc.org/github.com/golang/glog. This has worked for me for debugging: `</bin/provisioner> -alsologtostderr -v 5`.

I've seen various apps forcing stderr using this: https://github.com/kubernetes-csi/external-attacher/blob/master/cmd/csi-attacher/main.go#L88

(note that it's klog, not glog, but it should work in similar way).

**Comment by rajch** [comment]
I have also faced this problem. No matter what arguments I pass to my app, log messages in the controller _always_ go to log files only. Logging in my app itself respects the command line arguments.

**Comment by jsafrane** [comment]
Could it be caused by klog / glog mismatch in your app? lib-external-provisioner 
 switched to klog recently.

**Comment by rajch** [comment]
> Could it be caused by klog / glog mismatch in your app? lib-external-provisioner
> switched to klog recently.

Thank you. That was the problem.

**Comment by iyurev** [comment]
Thank you guys!  It solved my problem.
