### ISSUE TITLE
PV Protection breaks deleting

### ISSUE THREAD

**Issue by rmb938** [kubernetes-sigs/sig-storage-lib-external-provisioner#5]
If a user deletes a PV while it has a PVC with a pv protection finalizer the CSI never gets alerted to delete the volume when the pvc is deleted.

Related Issue: https://github.com/kubernetes-csi/external-provisioner/issues/195

It seems like https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go#L860 is the problem. 

Without a fix it is very easy for a user to delete a pv and break deleting via the CSI.

**Comment by msau42** [comment]
cc @wongma7 @jsafrane

**Comment by rmb938** [comment]
It probably would be useful to add external-provisioner finalizer and check if the existence of that. If it exists than delete the pv. If it doesn't return false as normal.
