### ISSUE TITLE
Deleting a PV with reclaim policy 'retain' does not delete backing volume

### ISSUE THREAD

**Issue by jfremy** [kubernetes-sigs/sig-storage-lib-external-provisioner#56]
I’ve been seeing something that looks like a weird behavior with dynamically provisioned volumes when their reclaimPolicy is set to retain.
If I delete a bound PVC and then delete the PV manually, the backing volume is not deleted by external-provisioner (it never issues a CSI deleteVolume call).
Reading the k8s doc about reclaimPolicy, my understanding is that it only represents the behavior of the PV in face of PVC deletion. But the PV <-> backing volume should not be impacted by it and a PV deletion should always trigger a backing volume deletion.

Looking at `sig-storage-lib-external-provisioner` used in external provisioner, I can see in the `(ctrl *ProvisionController) shouldDelete` function that if the PV’s reclaim policy is not DELETE, the provisioner will never delete the backing PV.

Did I understand the behavior wrong? Or should the code in shouldDelete be changed to account for “released” state of a volume and allow deletion in that case?

**Comment by wongma7** [comment]
Yes, you misunderstood. A PV is a one-way link/pointer to a backing volume. It exists solely so that kubernetes workloads can read/write it via a PVC. I would interpret the doc's omission of the PV deletion case to mean that nothing happens when a Released PV is deleted.

**Comment by Foxite** [comment]
Has this ever been up for debate? It would be convenient for me if backing assets were deleted by the provisioner, if I manually delete a PV after its PVCs were deleted. I have the reclaim policy on my storage classes set to Retain, so that the data does not disappear if I accidentally deleted a PVC.

I could potentially try to implement this myself, if there's no conceptual problems with it.

**Comment by rajch** [comment]
> Has this ever been up for debate? It would be convenient for me if backing assets were deleted by the provisioner, if I manually delete a PV after its PVCs were deleted. I have the reclaim policy on my storage classes set to Retain, so that the data does not disappear if I accidentally deleted a PVC.
> 
> I could potentially try to implement this myself, if there's no conceptual problems with it.
> 
> If this were to be implemented then it would have to be made optional in some way, so as not to break existing usages.

I understood the "Retain" reclaim policy to be just that - an option specifying that the backing storage will be deleted manually when needed.

**Comment by Foxite** [comment]
I personally understood it to mean that the PV would be retained, and manually deleted, if the PVC was deleted.
