### ISSUE TITLE
NFS Provisioner support for PersistentVolume Resizing?

### ISSUE THREAD

**Issue by ankitjain87** [kubernetes-sigs/sig-storage-lib-external-provisioner#72]
Hi, 

I am using NFS provisioner to provision PersistentVolume, and k8s now supports volume resizing, I was thinking if NFS Provisioner supports that? From the code, it looks it doesn't. Just wanted to know is there any plan to support the resizing?

Ref - https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

Thanks!

**Comment by zhucan** [comment]
I think only  csi driver supports controllerExpandVolume is ok to resize nfs pvc.
