### ISSUE TITLE
Use klog instead of glog

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/sig-storage-lib-external-provisioner#77]
I think logs from the library are not getting printed out with csi-provisioner because of this.

/kind cleanup
/help

**Comment by hzliangbin** [comment]
@msau42 there was a PR #21 related to this issue but closed.

**Comment by msau42** [comment]
Unsure why it was closed. @humblec do you have background on that?

**Comment by humblec** [comment]
> Unsure why it was closed. @humblec do you have background on that?

Neither me :(. Quite old PR and attempt so forgot the exact reason. I would have marked why it was closed in the PR comment atleast. Any way,  reopening and working on getting it done.

**Comment by hzliangbin** [comment]
@msau42  @humblec  The upstream k8s project has updated from klog v1 to klog v2. maybe we should migrate glog to klog v2.

kubernetes/kubernetes#90183

**Comment by msau42** [comment]
This should be addressed now
/close
