### ISSUE TITLE
Conflicting READMEs leave reader in infinite loop

### ISSUE THREAD

**Issue by c-x-berger** [kubernetes-sigs/sig-storage-lib-external-provisioner#85]
According to this repo's current README:

> A library for writing [external provisioners](https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner). See [external-storage](https://github.com/kubernetes-incubator/external-storage) for community-maintained external provisioners that use this library.

However, the README on the referenced external-storage repository says the following:

> Although many of these recipes still work, this repo is now deprecated, moving work to https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner, come join us there !

There seems to be a vicious cycle here.

**Comment by jtackaberry** [comment]
I myself am caught in this loop, wondering what, if anything, will supplant the now-deprecated nfs-client-provisioner.

**Comment by marvelous-melanie** [comment]
Agreed. Spent way too much time trying to find a maintained NFS provisioner.

**Comment by jdmaguire** [comment]
I'm glad I'm not the only one confused.

**Comment by msau42** [comment]
@wongma7 @kmova can you help fix up the readmes to point to the new repos for the nfs provisioners?

**Comment by wongma7** [comment]
/assign

Yes let me clean it up

**Comment by wongma7** [comment]
PTAL https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/93 apologies for confusion caused : (

**Comment by jdmaguire** [comment]
Thanks @wongma7
