### ISSUE TITLE
RFC: Simplify class properties getters

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-lib-external-provisioner#9]
Currently, there are many private functions to retrieve properties of class:

- getStorageClassFields
- fetchReclaimPolicy
- fetchMountOptions
- fetchAllowedTopologies

This part of code has been duplicated many times: 

```go
    classObj, found, err := ctrl.classes.GetByKey(storageClassName)
    if err != nil {
        return nil, err
    }    
    if !found {
        return nil, fmt.Errorf("storageClass %q not found", storageClassName)
    }    

    switch class := classObj.(type) {
    case *storage.StorageClass:
        // action on *storage.StorageClass
    case *storagebeta.StorageClass:
        // action on *storagebeta.StorageClass
    } 
```

Actually, rest of function does not contain much logic code.

How about unify these into one function which just returns a `*storage.StorageClass` object with optional error? e.g. `getClass(name) (*storage.StorageClass, error)`

In this function, we can convert `*storagebeta.StorageClas` to `*storage.StorageClass` internally. Then, controller can act on one kind of storage class directly.

Alternatively, we can create a struct to contain all properties of class, but I don't think it is necessary, because storage.StorageClass includes all fields of *storagebeta.StorageClass.

**Comment by cofyc** [comment]
cc @wongma7 What do you think?

**Comment by wongma7** [comment]
this sgtm

**Comment by fatsheep9146** [comment]
I would like to help with this.
/cc @cofyc
