### ISSUE TITLE
cleanup aliases to glog

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/sig-storage-lib-external-provisioner#96]
There are areas of the code that aliased klog to glog because it would be too many lines to change. We should clean those up.

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/896be1e22d769b7f3e6d10a404b8323f0575ba82/controller/controller.go#L54

/help
/good-first-issue

**Comment by Evalle** [comment]
Hey @msau42 I can work on it.
/assign

**Comment by Evalle** [comment]
Hey guys, I'm pretty sure there was some misunderstanding :) I have assigned this issue for me and I can see that @lianghao208 has assigned it as well afterwards, and even created PR.  So @msau42 now you have two PR :)

**Comment by msau42** [comment]
Sorry for the confusion. Since @Evalle offered to help first I'm going to review his pr.

Also removing label to avoid further confusion
/remove-label help-wanted
